name: ai_helper
description: "تطبيق بدايتك - تقييم الاستعداد للزواج"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # UI basics
  google_fonts: ^8.0.2
  flutter_svg: ^2.0.9
  lottie: ^3.0.0

  # State Management
  provider: ^6.1.1

  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  dio: ^5.4.0
  intl: ^0.20.2
  url_launcher: ^6.2.4
  http: ^1.1.0
  sqflite: ^2.4.2
  path: ^1.9.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^6.3.0
  cloud_firestore: ^6.1.2
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  pdf: ^3.11.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

# ✅ إعدادات flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/applogo.jpeg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/applogo.jpeg"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - lib/data/questions_complete.json
    - lib/data/advice_data.json
    - assets/fonts/
    - assets/applogo.jpeg

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700